### ISSUE TITLE
Upgrade to C# 6.0

### ISSUE THREAD

**Issue by AlexArchive** [AlexArchive/Validator#25]
I am _really_ excited to upgrade this particular library to use C# 6.0. I must wait a little while, though. 

I do not think it's a good idea to upgrade until the language is a little bit more mature.

**Comment by mgmccarthy** [comment]
AlexArchive, I'd be interested in helping with this when you're ready. Thanks

**Comment by ledbutter** [comment]
@mgmccarthy Thanks for expressing interest, if you are interested in upgrading to C# 6.0 and the accompanying simplifications that would be possible, please feel free to do so and PR it. Alex passed off maintenance of this project to me and I've been busy with other things so haven't had much time to work on this.

**Comment by ledbutter** [comment]
Addressed in PR #43
