### ISSUE TITLE
Extension methods

### ISSUE THREAD

**Issue by AlexArchive** [AlexArchive/Validator#26]
Someone else bought this up privately, and I am inclined to agree, we should make the validation methods available as extension methods.

I do not want to do this _quite_ yet, though.

I'm not certain where this library is going at the moment. I want to "shape" it some more before I make any infrastructural changes like the one described here.

**Comment by hanu412** [comment]
Hey...I actually wrote some extension methods which I used for my custom validation. Would you be interested in incorporating these?
Ex :  public static bool IsInteger(this string propValue)
        {
            if (string.IsNullOrWhiteSpace(propValue)) return false;
            int result = 0;
            bool isValidInteger = int.TryParse(propValue, out result);
            return isValidInteger;
        }

**Comment by ledbutter** [comment]
@hanu412 Submit it as a PR and we can discuss.

**Comment by mgmccarthy** [comment]
@ledbutter, do you still want a PR of this as extension methods? Just thinking the extension methods would get lost in the "noise" of the other members you would see via intellisense when typing:
[string].[list of stuff]. 

Not too sure of the added value here, but it would be nice to not have to reach out to Validator in order to feed it a value.

**Comment by ledbutter** [comment]
@mgmccarthy Sorry for the delayed response, I was out of the country on vacation last week. If you are interested in implementing these as extension methods, then go for it and PR it.

**Comment by mgmccarthy** [comment]
@ledbutter. PR submitted for extension methods. Also, it would be nice to break up the ValidatorTests class file into smaller files that matched the Validator partial classes. An example would be: IsBase64ValidatorTests, IsCreditCardValidatorTests, IsIsFqdnValidatorTests, etc... would be a lot easier to work with more granular test classes than all the tests crammed into one file. Just a suggestion
